version: 2.1

jobs:
  tests:
    docker:
      - image: circleci/golang:1.13
    environment:
      GOBIN: /go/bin
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache-{{ checksum "go.sum" }}
      - run: mkdir -p $TEST_RESULTS
      - run: make install
      - run:
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test -cover -race -coverprofile=${TEST_RESULTS}/coverage.out -v ./... | tee ${TEST_RESULTS}/go-test.out
      - run:
          command: |
            [ ! -z "${COVERALLS_TOKEN}" ] && goveralls -coverprofile=${TEST_RESULTS}/coverage.out -service=circle-ci -repotoken="${COVERALLS_TOKEN}"
      - save_cache:
          key: v1-pkg-cache-{{ checksum "go.sum" }}
          paths:
            - /go/pkg
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build:
    jobs:
      - tests
